import React, { createContext, useContext, useState, useEffect } from 'react';
import { LOCALES } from '../locales';

export type LanguageCode =
  | 'en' // English
  | 'hi' // Hindi
  | 'te' // Telugu
  | 'ta' // Tamil
  | 'pa' // Punjabi
  | 'mr' // Marathi
  | 'bn' // Bengali
  | 'gu' // Gujarati
  | 'kn' // Kannada
  | 'ml' // Malayalam
  | 'or' // Odia
  | 'as' // Assamese
  | 'ur' // Urdu
  | 'sa' // Sanskrit
  | 'bho' // Bhojpuri
  | 'ma'; // Maithili

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  direction?: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇮🇳', direction: 'rtl' },
  { code: 'bho', name: 'Bhojpuri', nativeName: 'भोजपुरी', flag: '🇮🇳' },
  { code: 'ma', name: 'Maithili', nativeName: 'मैथिली', flag: '🇮🇳' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्', flag: '🇮🇳' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation & General
    'platform.title': 'Public Agricultural Procurement Platform',
    'nav.home': 'Home',
    'nav.centres': 'Centres',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.register': 'Register as Farmer',
    'nav.my_bookings': 'My Bookings',
    'nav.live_queue': 'Live Queue',
    'nav.transactions': 'Transactions',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Farmer Profile',
    'nav.logout': 'Sign Out',
    'theme.dark': 'Dark Mode',
    'theme.light': 'Light Mode',

    // Hero & Home
    'hero.headline': 'Smart Procurement. Less Waiting.',
    'hero.subheadline': 'Book your procurement slot, track your live queue, and follow every step from check-in to payment — without crowding the counter.',
    'hero.register': 'Register as Farmer',
    'hero.find_centres': 'Find a Procurement Centre',
    'hero.easy_booking': 'Easy Slot Booking',
    'hero.live_queue': 'Live Queue Tracking',
    'hero.transparent_payments': 'Transparent Payments',
    'hero.realtime_notifications': 'Real-time Notifications',
    'hero.trusted_farmers': 'Trusted by Farmers Across India',
    'stats.centres': 'Procurement Centres',
    'stats.centres_sub': 'Across India',
    'stats.farmers': 'Farmers Registered',
    'stats.farmers_sub': 'Growing Community',
    'stats.transactions': 'Transactions Completed',
    'stats.transactions_sub': 'Successful Procurements',
    'stats.satisfaction': 'Farmer Satisfaction',
    'stats.satisfaction_sub': 'Happy Farmers',
    'how_it_works.title': 'How It Works',
    'step1.title': 'Register',
    'step1.desc': 'Create your verified account with land & bank details',
    'step2.title': 'Find a Centre',
    'step2.desc': 'Search and choose a nearby certified APMC / FCI centre',
    'step3.title': 'Book a Slot',
    'step3.desc': 'Select convenient delivery date, time & estimated harvest quantity',
    'step4.title': 'Track & Get Paid',
    'step4.desc': 'Track live queue token and receive direct DBT bank payment within 48h',
    'cta.banner_title': 'Skip the waiting. Plan your procurement.',
    'cta.banner_subtitle': 'A smarter digital way to deliver produce with zero congestion and guaranteed fair MSP returns.',
    'cta.banner_button': 'Book Your Slot Now',

    // Dashboard
    'dash.welcome_back': 'Welcome back,',
    'dash.welcome_default': 'Welcome to AgriSetu',
    'dash.subtitle': "Here's what's happening with your crops, queue schedules, and payments today.",
    'dash.upcoming_booking': 'Upcoming Booking',
    'dash.live_queue_pos': 'Live Queue Pos',
    'dash.completed_txns': 'Completed Txns',
    'dash.total_payments': 'Direct DBT Payouts',
    'dash.quick_actions': 'Quick Actions',
    'dash.book_slot': 'Book New Slot',
    'dash.find_centres': 'Find Mandi / Silo',
    'dash.track_queue': 'Live Queue Tracker',
    'dash.view_txns': 'Payment Receipts',
    'dash.active_booking': 'Active Booking & Gate Pass',
    'dash.recent_bookings': 'Recent Bookings',
    'dash.view_all': 'View All',
    'dash.no_bookings': 'No recent bookings found. Schedule your harvest delivery today!',
    'dash.check_in_now': 'Check In Now',
    'dash.view_pass': 'View Token Pass',
    'dash.token': 'Token',
    'dash.date': 'Date',
    'dash.centre': 'Centre',
    'dash.crop': 'Crop',
    'dash.quantity': 'Quantity',
    'dash.status': 'Status',
    'dash.actions': 'Actions',

    // Booking Flow
    'booking.title': 'Schedule Crop Procurement Slot',
    'booking.subtitle': 'Book your guaranteed mandi delivery slot and skip vehicle congestion at the gate.',
    'booking.step1': '1. Select Centre',
    'booking.step2': '2. Date & Time Slot',
    'booking.step3': '3. Crop & Vehicle Details',
    'booking.filter_state': 'Filter by State',
    'booking.filter_district': 'Filter by District',
    'booking.search_centres': 'Search centre by name or location...',
    'booking.centre_selected': 'Selected Centre',
    'booking.change_centre': 'Change Centre',
    'booking.select_date': 'Select Delivery Date',
    'booking.select_slot': 'Select Time Slot',
    'booking.morning_slots': 'Morning Slots (8:00 AM - 12:00 PM)',
    'booking.afternoon_slots': 'Afternoon Slots (12:00 PM - 4:00 PM)',
    'booking.evening_slots': 'Evening Slots (4:00 PM - 7:00 PM)',
    'booking.slots_available': 'slots available',
    'booking.slot_full': 'Slot Full',
    'booking.crop_type': 'Crop to Deliver',
    'booking.quantity': 'Estimated Harvest Quantity (Quintals)',
    'booking.vehicle_no': 'Tractor / Vehicle Number',
    'booking.vehicle_placeholder': 'e.g. AP 31 AB 1234 or HR 05 T 5678',
    'booking.review_title': 'Booking Review Summary',
    'booking.est_msp_payout': 'Estimated MSP Direct Payout',
    'booking.confirm_btn': 'Confirm & Reserve Slot',
    'booking.back_btn': 'Back',
    'booking.next_btn': 'Continue',
    'booking.err_select_slot': 'Please select a date and time slot.',
    'booking.err_quantity': 'Please enter a valid harvest quantity.',
    'booking.success_title': 'Booking Confirmed!',
    'booking.success_sub': 'Your slot has been successfully scheduled. Please show your queue token upon arrival at the gate.',
    'booking.token_allocated': 'Queue Token Allocated',
    'booking.ref_number': 'Booking Reference',
    'booking.print_pass': 'Download / Print Pass',
    'booking.view_live_queue': 'Go to Live Queue Tracker',
    'booking.return_dashboard': 'Back to Dashboard',
    'booking.cancel_modal_title': 'Are you sure you want to cancel?',
    'booking.cancel_modal_desc': 'Your current booking progress will be lost.',
    'booking.continue_booking_btn': 'Continue Booking',
    'booking.yes_cancel_btn': 'Yes, Cancel',

    // Live Queue Tracker
    'queue.title': 'Live Queue & Token Tracker',
    'queue.subtitle': 'Real-time updates on weighbridge progress and counter inspection.',
    'queue.your_token': 'Your Queue Token',
    'queue.estimated_wait': 'Estimated Gate Wait',
    'queue.vehicles_ahead': 'Vehicles Ahead',
    'queue.step_checkin': 'Gate Check-in',
    'queue.step_quality': 'Moisture & Quality Assay',
    'queue.step_weighbridge': 'Gross & Tare Weighbridge',
    'queue.step_jform': 'J-Form / Procurement Slip',
    'queue.step_payment': 'PFMS Bank Transfer',
    'queue.current_stage': 'Current Stage',
    'queue.completed': 'Completed',
    'queue.in_progress': 'In Progress',
    'queue.upcoming': 'Upcoming',

    // My Bookings
    'bookings.title': 'My Procurement Bookings',
    'bookings.subtitle': 'Manage your scheduled visits, view gate passes, and track status.',
    'bookings.all': 'All Bookings',
    'bookings.confirmed': 'Confirmed',
    'bookings.checked_in': 'Checked In',
    'bookings.completed': 'Completed',
    'bookings.cancelled': 'Cancelled',
    'bookings.cancel_slot': 'Cancel Slot',
    'bookings.reschedule': 'Reschedule',

    // Transactions & DBT
    'txns.title': 'Procurement Payments & DBT Records',
    'txns.subtitle': 'Transparent direct-benefit transfer records with official MSP settlement slips.',
    'txns.total_credited': 'Total Amount Credited',
    'txns.pending_credits': 'Processing in PFMS',
    'txns.view_receipt': 'Download J-Form / Receipt',
    'txns.msp_rate': 'MSP Rate Applied',
    'txns.status_credited': 'Directly Credited to Bank',
    'txns.status_processing': 'Processing via PFMS',

    // Profile
    'profile.title': 'Farmer Profile & Identity',
    'profile.subtitle': 'Manage your verified farmer ID, land holdings, bank DBT account, and notification preferences.',
    'profile.tab_personal': 'Personal Details',
    'profile.tab_farm': 'Land & Farm Holdings',
    'profile.tab_bank': 'Bank & DBT Account',
    'profile.tab_documents': 'KYC & Land Records',
    'profile.tab_preferences': 'Preferences',
    'profile.full_name': 'Full Name (as per Aadhaar)',
    'profile.mobile': 'Mobile Number (OTP Linked)',
    'profile.aadhaar': 'Aadhaar / Farmer ID',
    'profile.village': 'Village / Street Address',
    'profile.district': 'District',
    'profile.state': 'State',
    'profile.pincode': 'PIN Code',
    'profile.land_size': 'Total Land Size (Acres)',
    'profile.survey_no': 'Khata / Survey Number',
    'profile.ownership': 'Ownership Type',
    'profile.primary_crops': 'Primary Crops Grown',
    'profile.bank_name': 'Bank Name',
    'profile.account_no': 'Account Number',
    'profile.ifsc': 'IFSC Code',
    'profile.upi_id': 'UPI ID (Optional)',
    'profile.dbt_linked': 'Aadhaar DBT Enabled',
    'profile.save_changes': 'Save Profile Changes',
    'profile.saving': 'Saving...',
    'profile.saved_success': 'Profile updated successfully!',
    'profile.view_id_card': 'View Farmer ID Card',

    // Auth
    'auth.login_title': 'Farmer Portal Login',
    'auth.login_subtitle': 'Access your procurement dashboard, book slots, and track payments.',
    'auth.phone_placeholder': 'Mobile Number or Farmer ID',
    'auth.password': 'Password / PIN',
    'auth.login_btn': 'Sign In',
    'auth.register_title': 'Farmer Registration',
    'auth.register_subtitle': 'Register to book procurement slots and receive direct MSP payments.',
    'auth.register_btn': 'Complete Registration',
    'auth.already_account': 'Already registered? Sign in',
    'auth.new_farmer': 'New farmer? Register here',
  },

  hi: {
    // Navigation & General
    'platform.title': 'सार्वजनिक कृषि खरीद मंच',
    'nav.home': 'होम',
    'nav.centres': 'खरीद केंद्र',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क करें',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.login': 'लॉगिन',
    'nav.register': 'किसान पंजीकरण',
    'nav.my_bookings': 'मेरी बुकिंग',
    'nav.live_queue': 'लाइव कतार',
    'nav.transactions': 'लेनदेन एवं भुगतान',
    'nav.notifications': 'सूचनाएं',
    'nav.profile': 'किसान प्रोफाइल',
    'nav.logout': 'लॉग आउट',
    'theme.dark': 'डार्क मोड',
    'theme.light': 'लाइट मोड',

    // Hero & Home
    'hero.headline': 'स्मार्ट खरीद। कम इंतज़ार।',
    'hero.subheadline': 'अपनी खरीद का स्लॉट बुक करें, लाइव कतार ट्रैक करें, और चेक-इन से लेकर भुगतान तक हर कदम का पालन करें — बिना मंडी में भीड़ लगाए।',
    'hero.register': 'किसान पंजीकरण करें',
    'hero.find_centres': 'खरीद केंद्र खोजें',
    'hero.easy_booking': 'आसान स्लॉट बुकिंग',
    'hero.live_queue': 'लाइव कतार ट्रैकिंग',
    'hero.transparent_payments': 'पारदर्शी भुगतान',
    'hero.realtime_notifications': 'त्वरित सूचनाएं',
    'hero.trusted_farmers': 'पूरे भारत के किसानों का भरोसा',
    'stats.centres': 'खरीद केंद्र',
    'stats.centres_sub': 'पूरे भारत में',
    'stats.farmers': 'पंजीकृत किसान',
    'stats.farmers_sub': 'बढ़ता हुआ समुदाय',
    'stats.transactions': 'सफल लेनदेन',
    'stats.transactions_sub': 'सफल खरीद प्रक्रियाएं',
    'stats.satisfaction': 'किसान संतुष्टि',
    'stats.satisfaction_sub': 'संतुष्ट किसान',
    'how_it_works.title': 'यह कैसे काम करता है',
    'step1.title': 'पंजीकरण करें',
    'step1.desc': 'भूमि और बैंक विवरण के साथ अपना सत्यापित खाता बनाएं',
    'step2.title': 'केंद्र चुनें',
    'step2.desc': 'नजदीकी प्रमाणित एपीएमसी / एफसीआई केंद्र खोजें और चुनें',
    'step3.title': 'स्लॉट बुक करें',
    'step3.desc': 'सुविधाजनक तारीख, समय और अनुमानित फसल मात्रा चुनें',
    'step4.title': 'ट्रैक करें और भुगतान पाएं',
    'step4.desc': 'लाइव कतार टोकन ट्रैक करें और 48 घंटे में सीधे बैंक खाते में भुगतान पाएं',
    'cta.banner_title': 'लाइन में लगना छोड़ें। खरीद की योजना बनाएं।',
    'cta.banner_subtitle': 'मंडी में बिना भीड़ के अपनी उपज बेचने और सीधा सरकारी एमएसपी भुगतान पाने का डिजिटल तरीका।',
    'cta.banner_button': 'अभी अपना स्लॉट बुक करें',

    // Dashboard
    'dash.welcome_back': 'वापसी पर स्वागत है,',
    'dash.welcome_default': 'फ़ार्मलिंक कनेक्ट में आपका स्वागत है',
    'dash.subtitle': 'आज आपकी फसलों, कतार समय और भुगतान की स्थिति यहाँ देखें।',
    'dash.upcoming_booking': 'आगामी बुकिंग',
    'dash.live_queue_pos': 'लाइव कतार संख्या',
    'dash.completed_txns': 'पूर्ण लेनदेन',
    'dash.total_payments': 'कुल डीबीटी भुगतान',
    'dash.quick_actions': 'त्वरित कार्य',
    'dash.book_slot': 'नया स्लॉट बुक करें',
    'dash.find_centres': 'मंडी / केंद्र खोजें',
    'dash.track_queue': 'लाइव कतार ट्रैकर',
    'dash.view_txns': 'भुगतान रसीदें',
    'dash.active_booking': 'सक्रिय बुकिंग एवं गेट पास',
    'dash.recent_bookings': 'हाल की बुकिंग्स',
    'dash.view_all': 'सभी देखें',
    'dash.no_bookings': 'कोई हालिया बुकिंग नहीं मिली। आज ही अपनी फसल डिलीवरी शेड्यूल करें!',
    'dash.check_in_now': 'अभी चेक-इन करें',
    'dash.view_pass': 'टोकन पास देखें',
    'dash.token': 'टोकन',
    'dash.date': 'तारीख',
    'dash.centre': 'केंद्र',
    'dash.crop': 'फसल',
    'dash.quantity': 'मात्रा',
    'dash.status': 'स्थिति',
    'dash.actions': 'कार्य',

    // Booking Flow
    'booking.title': 'फसल खरीद स्लॉट बुक करें',
    'booking.subtitle': 'अपनी मंडी डिलीवरी का समय पहले से आरक्षित करें और गेट पर इंतज़ार से बचें।',
    'booking.step1': '1. खरीद केंद्र चुनें',
    'booking.step2': '2. तारीख और समय स्लॉट',
    'booking.step3': '3. फसल और वाहन विवरण',
    'booking.filter_state': 'राज्य अनुसार खोजें',
    'booking.filter_district': 'जिला अनुसार खोजें',
    'booking.search_centres': 'नाम या स्थान से केंद्र खोजें...',
    'booking.centre_selected': 'चुना गया केंद्र',
    'booking.change_centre': 'केंद्र बदलें',
    'booking.select_date': 'डिलीवरी तारीख चुनें',
    'booking.select_slot': 'समय स्लॉट चुनें',
    'booking.morning_slots': 'सुबह का समय (8:00 AM - 12:00 PM)',
    'booking.afternoon_slots': 'दोपहर का समय (12:00 PM - 4:00 PM)',
    'booking.evening_slots': 'शाम का समय (4:00 PM - 7:00 PM)',
    'booking.slots_available': 'स्लॉट उपलब्ध',
    'booking.slot_full': 'स्लॉट भर चुका है',
    'booking.crop_type': 'लाई जाने वाली फसल',
    'booking.quantity': 'अनुमानित फसल मात्रा (क्विंटल)',
    'booking.vehicle_no': 'ट्रैक्टर / वाहन नंबर',
    'booking.vehicle_placeholder': 'उदा. UP 32 AB 1234 या HR 05 T 5678',
    'booking.review_title': 'बुकिंग सारांश विवरण',
    'booking.est_msp_payout': 'अनुमानित एमएसपी सीधा भुगतान',
    'booking.confirm_btn': 'स्लॉट सुरक्षित करें और पुष्टि करें',
    'booking.back_btn': 'पीछे',
    'booking.next_btn': 'आगे बढ़ें',
    'booking.err_select_slot': 'कृपया तारीख और समय स्लॉट चुनें।',
    'booking.err_quantity': 'कृपया फसल की मान्य मात्रा दर्ज करें।',
    'booking.success_title': 'बुकिंग सफलतापूर्वक हो गई!',
    'booking.success_sub': 'आपका स्लॉट बुक हो गया है। कृपया मंडी गेट पर अपना कतार टोकन दिखाएं।',
    'booking.token_allocated': 'आवंटित कतार टोकन',
    'booking.ref_number': 'बुकिंग संदर्भ संख्या',
    'booking.print_pass': 'गेट पास डाउनलोड / प्रिंट करें',
    'booking.view_live_queue': 'लाइव कतार स्थिति देखें',
    'booking.return_dashboard': 'डैशबोर्ड पर वापस जाएं',

    // Live Queue Tracker
    'queue.title': 'लाइव कतार एवं टोकन ट्रैकर',
    'queue.subtitle': 'वेब्रिज और मंडी गुणवत्ता जांच की रीयल-टाइम स्थिति।',
    'queue.your_token': 'आपका कतार टोकन',
    'queue.estimated_wait': 'अनुमानित इंतज़ार समय',
    'queue.vehicles_ahead': 'आगे खड़े वाहन',
    'queue.step_checkin': 'गेट चेक-इन',
    'queue.step_quality': 'नमी एवं गुणवत्ता परीक्षण',
    'queue.step_weighbridge': 'वेब्रिज वजन (कांटा)',
    'queue.step_jform': 'जे-फॉर्म / खरीद रसीद',
    'queue.step_payment': 'सीधा बैंक खाता ट्रांसफर',
    'queue.current_stage': 'वर्तमान चरण',
    'queue.completed': 'पूर्ण',
    'queue.in_progress': 'प्रगति पर',
    'queue.upcoming': 'आगामी',

    // My Bookings
    'bookings.title': 'मेरी खरीद बुकिंग्स',
    'bookings.subtitle': 'अपने निर्धारित समय, गेट पास और खरीद की स्थिति देखें।',
    'bookings.all': 'सभी बुकिंग्स',
    'bookings.confirmed': 'पुष्ट (Confirmed)',
    'bookings.checked_in': 'चेक-इन हुआ',
    'bookings.completed': 'पूर्ण हुई',
    'bookings.cancelled': 'रद्द हुई',
    'bookings.cancel_slot': 'स्लॉट रद्द करें',
    'bookings.reschedule': 'तारीख बदलें',

    // Transactions & DBT
    'txns.title': 'खरीद भुगतान एवं डीबीटी रिकॉर्ड',
    'txns.subtitle': 'सरकारी एमएसपी दरों पर सीधे बैंक खाते में जमा राशि और रसीदें।',
    'txns.total_credited': 'कुल प्राप्त भुगतान',
    'txns.pending_credits': 'प्रक्रियाधीन राशि',
    'txns.view_receipt': 'जे-फॉर्म रसीद डाउनलोड करें',
    'txns.msp_rate': 'लागू एमएसपी दर',
    'txns.status_credited': 'बैंक में जमा हो चुका है',
    'txns.status_processing': 'पीएफएमएस द्वारा प्रक्रियाधीन',

    // Profile
    'profile.title': 'किसान प्रोफाइल एवं पहचान',
    'profile.subtitle': 'अपनी किसान आईडी, भूमि रिकॉर्ड, बैंक खाता और सूचनाएं प्रबंधित करें।',
    'profile.tab_personal': 'व्यक्तिगत विवरण',
    'profile.tab_farm': 'भूमि एवं फसल विवरण',
    'profile.tab_bank': 'बैंक खाता एवं डीबीटी',
    'profile.tab_documents': 'दस्तावेज़ एवं केवाईसी',
    'profile.tab_preferences': 'प्राथमिकताएं',
    'profile.full_name': 'पूरा नाम (आधार अनुसार)',
    'profile.mobile': 'मोबाइल नंबर',
    'profile.aadhaar': 'आधार / किसान आईडी',
    'profile.village': 'गाँव / पता',
    'profile.district': 'जिला',
    'profile.state': 'राज्य',
    'profile.pincode': 'पिन कोड',
    'profile.land_size': 'कुल भूमि (एकड़)',
    'profile.survey_no': 'खसरा / खाता संख्या',
    'profile.ownership': 'स्वामित्व का प्रकार',
    'profile.primary_crops': 'मुख्य फसलें',
    'profile.bank_name': 'बैंक का नाम',
    'profile.account_no': 'खाता संख्या',
    'profile.ifsc': 'आईएफएससी कोड',
    'profile.upi_id': 'यूपीआई आईडी (वैकल्पिक)',
    'profile.dbt_linked': 'आधार डीबीटी सक्रिय',
    'profile.save_changes': 'विवरण सहेजें',
    'profile.saving': 'सहेजा जा रहा है...',
    'profile.saved_success': 'प्रोफाइल सफलतापूर्वक अपडेट हो गई!',
    'profile.view_id_card': 'किसान पहचान पत्र देखें',

    // Auth
    'auth.login_title': 'किसान पोर्टल लॉगिन',
    'auth.login_subtitle': 'अपने डैशबोर्ड पर जाएं, स्लॉट बुक करें और भुगतान ट्रैक करें।',
    'auth.phone_placeholder': 'मोबाइल नंबर या किसान आईडी',
    'auth.password': 'पासवर्ड / पिन',
    'auth.login_btn': 'साइन इन करें',
    'auth.register_title': 'नया किसान पंजीकरण',
    'auth.register_subtitle': 'स्लॉट बुक करने और सीधा सरकारी भुगतान पाने के लिए पंजीकरण करें।',
    'auth.register_btn': 'पंजीकरण पूरा करें',
    'auth.already_account': 'पहले से पंजीकृत हैं? लॉगिन करें',
    'auth.new_farmer': 'नए किसान हैं? यहाँ पंजीकरण करें',
  },

  te: {
    // Navigation & General
    'platform.title': 'ప్రజా వ్యవసాయ సేకరణ వేదిక',
    'nav.home': 'హోమ్',
    'nav.centres': 'కొనుగోలు కేంద్రాలు',
    'nav.about': 'మా గురించి',
    'nav.contact': 'సంప్రదించండి',
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.login': 'లాగిన్',
    'nav.register': 'రైతు నమోదు',
    'nav.my_bookings': 'నా బుకింగ్‌లు',
    'nav.live_queue': 'లైవ్ క్యూ',
    'nav.transactions': 'లావాదేవీలు',
    'nav.notifications': 'నోటిఫికేషన్లు',
    'nav.profile': 'రైతు ప్రొఫైల్',
    'nav.logout': 'లాగ్ అవుట్',
    'theme.dark': 'డార్క్ మోడ్',
    'theme.light': 'లైట్ మోడ్',

    // Hero & Home
    'hero.headline': 'స్మార్ట్ కొనుగోలు. తక్కువ వేచి ఉండే సమయం.',
    'hero.subheadline': 'మీ ధాన్యం విక్రయ స్లాట్‌ను బుక్ చేసుకోండి, లైవ్ క్యూను ట్రాక్ చేయండి మరియు చెక్-ఇన్ నుండి నేరుగా బ్యాంక్ ఖాతాలో జమ అయ్యే వరకు ప్రతి దశను సులభంగా అనుసరించండి.',
    'hero.register': 'రైతుగా నమోదు చేసుకోండి',
    'hero.find_centres': 'కొనుగోలు కేంద్రాన్ని కనుగొనండి',
    'hero.easy_booking': 'సులభమైన స్లాట్ బుకింగ్',
    'hero.live_queue': 'లైవ్ క్యూ ట్రాకింగ్',
    'hero.transparent_payments': 'పారదర్శక చెల్లింపులు',
    'hero.realtime_notifications': 'తక్షణ సమాచారం',
    'hero.trusted_farmers': 'భారతదేశవ్యాప్తంగా రైతుల విశ్వాసం',
    'stats.centres': 'కొనుగోలు కేంద్రాలు',
    'stats.centres_sub': 'దేశవ్యాప్తంగా',
    'stats.farmers': 'నమోదైన రైతులు',
    'stats.farmers_sub': 'విస్తరిస్తున్న సమాజం',
    'stats.transactions': 'పూర్తయిన లావాదేవీలు',
    'stats.transactions_sub': 'విజయవంతమైన సేకరణలు',
    'stats.satisfaction': 'రైతుల సంతృప్తి',
    'stats.satisfaction_sub': 'సంతృప్తి చెందిన రైతులు',
    'how_it_works.title': 'ఇది ఎలా పనిచేస్తుంది',
    'step1.title': 'నమోదు చేసుకోండి',
    'step1.desc': 'భూమి మరియు బ్యాంక్ వివరాలతో ఖాతాను సృష్టించండి',
    'step2.title': 'కేంద్రాన్ని ఎంచుకోండి',
    'step2.desc': 'సమీపంలోని మార్కెట్ యార్డ్ / కొనుగోలు కేంద్రాన్ని ఎంచుకోండి',
    'step3.title': 'స్లాట్ బుక్ చేయండి',
    'step3.desc': 'తేదీ, సమయం మరియు అంచనా వేసిన పంట పరిమాణాన్ని ఎంచుకోండి',
    'step4.title': 'ట్రాక్ చేసి డబ్బులు పొందండి',
    'step4.desc': 'లైవ్ క్యూను ట్రాక్ చేయండి మరియు 48 గంటల్లో నేరుగా మీ బ్యాంక్ ఖాతాలో మద్దతు ధర పొందండి',
    'cta.banner_title': 'వేచి ఉండటం వద్దు. మీ విక్రయాన్ని ప్లాన్ చేసుకోండి.',
    'cta.banner_subtitle': 'రైతు బజార్లలో రద్దీ లేకుండా మద్దతు ధరను నేరుగా పొందడానికి స్మార్ట్ మార్గం.',
    'cta.banner_button': 'ఇప్పుడే మీ స్లాట్ బుక్ చేసుకోండి',

    // Dashboard
    'dash.welcome_back': 'స్వాగతం,',
    'dash.welcome_default': 'ఫార్మ్‌లింక్ కనెక్ట్‌కు స్వాగతం',
    'dash.subtitle': 'ఈరోజు మీ పంటలు, క్యూ షెడ్యూల్‌లు మరియు చెల్లింపుల సమాచారం ఇక్కడ ఉంది.',
    'dash.upcoming_booking': 'రాబోయే బుకింగ్',
    'dash.live_queue_pos': 'లైవ్ క్యూ స్థానం',
    'dash.completed_txns': 'పూర్తయిన అమ్మకాలు',
    'dash.total_payments': 'నేరుగా అందిన మొత్తం',
    'dash.quick_actions': 'త్వరిత చర్యలు',
    'dash.book_slot': 'కొత్త స్లాట్ బుక్ చేయండి',
    'dash.find_centres': 'కేంద్రాన్ని వెతకండి',
    'dash.track_queue': 'లైవ్ క్యూ ట్రాకర్',
    'dash.view_txns': 'చెల్లింపు రసీదులు',
    'dash.active_booking': 'ప్రస్తుత బుకింగ్ & గేట్ పాస్',
    'dash.recent_bookings': 'ఇటీవలి బుకింగ్‌లు',
    'dash.view_all': 'అన్నీ చూడండి',
    'dash.no_bookings': 'ఇటీవలి బుకింగ్‌లు ఏవీ లేవు. ఈరోజే మీ పంట డెలివరీని షెడ్యూల్ చేసుకోండి!',
    'dash.check_in_now': 'ఇప్పుడే చెక్-ఇన్ చేయండి',
    'dash.view_pass': 'టోకెన్ పాస్ చూడండి',
    'dash.token': 'టోకెన్',
    'dash.date': 'తేదీ',
    'dash.centre': 'కేంద్రం',
    'dash.crop': 'పంట',
    'dash.quantity': 'పరిమాణం',
    'dash.status': 'స్థితి',
    'dash.actions': 'చర్యలు',

    // Booking Flow
    'booking.title': 'పంట కొనుగోలు స్లాట్ బుకింగ్',
    'booking.subtitle': 'మీ డెలివరీ సమయాన్ని ముందుగానే రిజర్వ్ చేసుకోండి మరియు గేట్ వద్ద ట్రాక్టర్ల రద్దీని నివారించండి.',
    'booking.step1': '1. కేంద్రాన్ని ఎంచుకోండి',
    'booking.step2': '2. తేదీ & సమయ స్లాట్',
    'booking.step3': '3. పంట మరియు వాహన వివరాలు',
    'booking.filter_state': 'రాష్ట్రం వారీగా',
    'booking.filter_district': 'జిల్లా వారీగా',
    'booking.search_centres': 'పేరు లేదా ప్రాంతం ద్వారా కేంద్రాన్ని వెతకండి...',
    'booking.centre_selected': 'ఎంచుకున్న కేంద్రం',
    'booking.change_centre': 'కేంద్రాన్ని మార్చండి',
    'booking.select_date': 'డెలివరీ తేదీని ఎంచుకోండి',
    'booking.select_slot': 'సమయ స్లాట్‌ను ఎంచుకోండి',
    'booking.morning_slots': 'ఉదయం స్లాట్‌లు (8:00 AM - 12:00 PM)',
    'booking.afternoon_slots': 'మధ్యాహ్నం స్లాట్‌లు (12:00 PM - 4:00 PM)',
    'booking.evening_slots': 'సాయంత్రం స్లాట్‌లు (4:00 PM - 7:00 PM)',
    'booking.slots_available': 'స్లాట్‌లు అందుబాటులో ఉన్నాయి',
    'booking.slot_full': 'స్లాట్ నిండిపోయింది',
    'booking.crop_type': 'డెలివరీ చేయవలసిన పంట',
    'booking.quantity': 'అంచనా వేసిన పంట పరిమాణం (క్వింటాళ్లలో)',
    'booking.vehicle_no': 'ట్రాక్టర్ / వాహనం నంబర్',
    'booking.vehicle_placeholder': 'ఉదా. AP 31 AB 1234 లేదా TS 08 AB 5678',
    'booking.review_title': 'బుకింగ్ సమీక్ష వివరాలు',
    'booking.est_msp_payout': 'అంచనా వేసిన ప్రభుత్వ మద్దతు ధర చెల్లింపు',
    'booking.confirm_btn': 'స్లాట్‌ను నిర్ధారించండి',
    'booking.back_btn': 'వెనుకకు',
    'booking.next_btn': 'కొనసాగించండి',
    'booking.err_select_slot': 'దయచేసి తేదీ మరియు సమయ స్లాట్‌ను ఎంచుకోండి.',
    'booking.err_quantity': 'దయచేసి సరైన పంట పరిమాణాన్ని నమోదు చేయండి.',
    'booking.success_title': 'బుకింగ్ విజయవంతంగా పూర్తయింది!',
    'booking.success_sub': 'మీ స్లాట్ రిజర్వ్ చేయబడింది. దయచేసి మార్కెట్ యార్డ్ గేట్ వద్ద మీ క్యూ టోకెన్ చూపించండి.',
    'booking.token_allocated': 'కేటాయించిన క్యూ టోకెన్',
    'booking.ref_number': 'బుకింగ్ రిఫరెన్స్ నంబర్',
    'booking.print_pass': 'గేట్ పాస్ డౌన్‌లోడ్ / ప్రింట్',
    'booking.view_live_queue': 'లైవ్ క్యూ ట్రాకర్‌కి వెళ్లండి',
    'booking.return_dashboard': 'డాష్‌బోర్డ్‌కి తిరిగి వెళ్లండి',

    // Live Queue Tracker
    'queue.title': 'లైవ్ క్యూ మరియు టోకెన్ స్థితి',
    'queue.subtitle': 'వేబ్రిడ్జ్ మరియు నాణ్యత తనిఖీ ప్రత్యక్ష సమాచారం.',
    'queue.your_token': 'మీ క్యూ టోకెన్',
    'queue.estimated_wait': 'అంచనా వేసిన వేచి ఉండే సమయం',
    'queue.vehicles_ahead': 'ముందున్న వాహనాలు',
    'queue.step_checkin': 'గేట్ చెక్-ఇన్',
    'queue.step_quality': 'తేమ & నాణ్యత పరీక్ష',
    'queue.step_weighbridge': 'వేబ్రిడ్జ్ కాటా (బరువు)',
    'queue.step_jform': 'జె-ఫారమ్ / సేకరణ రసీదు',
    'queue.step_payment': 'నేరుగా బ్యాంక్ బదిలీ',
    'queue.current_stage': 'ప్రస్తుత దశ',
    'queue.completed': 'పూర్తయింది',
    'queue.in_progress': 'పురోగతిలో ఉంది',
    'queue.upcoming': 'రాబోయేది',

    // My Bookings
    'bookings.title': 'నా సేకరణ బుకింగ్‌లు',
    'bookings.subtitle': 'మీ షెడ్యూల్ చేసిన సందర్శనలు, గేట్ పాస్‌లు మరియు స్థితిని నిర్వహించండి.',
    'bookings.all': 'అన్ని బుకింగ్‌లు',
    'bookings.confirmed': 'నిర్ధారించబడింది',
    'bookings.checked_in': 'చెక్-ఇన్ పూర్తయింది',
    'bookings.completed': 'పూర్తయింది',
    'bookings.cancelled': 'రద్దు చేయబడింది',
    'bookings.cancel_slot': 'స్లాట్‌ను రద్దు చేయండి',
    'bookings.reschedule': 'తేదీని మార్చండి',

    // Transactions & DBT
    'txns.title': 'చెల్లింపులు & DBT రికార్డులు',
    'txns.subtitle': 'ప్రభుత్వ కనీస మద్దతు ధరతో నేరుగా బ్యాంక్ ఖాతాలో జమ అయిన వివరాలు.',
    'txns.total_credited': 'మొత్తం జమ అయిన నగదు',
    'txns.pending_credits': 'PFMS ప్రాసెసింగ్‌లో ఉన్న మొత్తం',
    'txns.view_receipt': 'జె-ఫారమ్ రసీదు డౌన్‌లోడ్',
    'txns.msp_rate': 'వర్తించిన MSP ధర',
    'txns.status_credited': 'బ్యాంక్ ఖాతాలో జమ చేయబడింది',
    'txns.status_processing': 'PFMS ద్వారా ప్రాసెస్ అవుతోంది',

    // Profile
    'profile.title': 'రైతు ప్రొఫైల్ & గుర్తింపు',
    'profile.subtitle': 'మీ రైతు ఐడీ, భూమి వివరాలు, బ్యాంక్ ఖాతా మరియు ప్రాధాన్యతలను నిర్వహించండి.',
    'profile.tab_personal': 'వ్యక్తిగత వివరాలు',
    'profile.tab_farm': 'భూమి మరియు పంట వివరాలు',
    'profile.tab_bank': 'బ్యాంక్ & DBT ఖాతా',
    'profile.tab_documents': 'పత్రాలు & కేవైసీ',
    'profile.tab_preferences': 'ప్రాధాన్యతలు',
    'profile.full_name': 'పూర్తి పేరు (ఆధార్ ప్రకారం)',
    'profile.mobile': 'మొబైల్ నంబర్',
    'profile.aadhaar': 'ఆధార్ / రైతు ఐడీ',
    'profile.village': 'గ్రామం / చిరునామా',
    'profile.district': 'జిల్లా',
    'profile.state': 'రాష్ట్రం',
    'profile.pincode': 'పిన్ కోడ్',
    'profile.land_size': 'మొత్తం భూమి (ఎకరాలు)',
    'profile.survey_no': 'సర్వే / ఖాతా నంబర్',
    'profile.ownership': 'యాజమాన్య రకం',
    'profile.primary_crops': 'ప్రధాన పంటలు',
    'profile.bank_name': 'బ్యాంకు పేరు',
    'profile.account_no': 'ఖాతా సంఖ్య',
    'profile.ifsc': 'IFSC కోడ్',
    'profile.upi_id': 'UPI ఐడీ (ఐచ్ఛికం)',
    'profile.dbt_linked': 'ఆధార్ DBT అనుసంధానమైంది',
    'profile.save_changes': 'వివరాలను భద్రపరచండి',
    'profile.saving': 'భద్రపరుస్తోంది...',
    'profile.saved_success': 'ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది!',
    'profile.view_id_card': 'రైతు గుర్తింపు కార్డు చూడండి',

    // Auth
    'auth.login_title': 'రైతు పోర్టల్ లాగిన్',
    'auth.login_subtitle': 'మీ డాష్‌బోర్డ్‌ని యాక్సెస్ చేయండి, స్లాట్‌లను బుక్ చేసుకోండి మరియు చెల్లింపులను ట్రాక్ చేయండి.',
    'auth.phone_placeholder': 'మొబైల్ నంబర్ లేదా రైతు ఐడీ',
    'auth.password': 'పాస్‌వర్డ్ / పిన్',
    'auth.login_btn': 'లాగిన్ అవ్వండి',
    'auth.register_title': 'రైతు నమోదు',
    'auth.register_subtitle': 'కొనుగోలు స్లాట్‌లను బుక్ చేసుకోవడానికి మరియు నేరుగా MSP పొందడానికి నమోదు చేసుకోండి.',
    'auth.register_btn': 'నమోదు పూర్తి చేయండి',
    'auth.already_account': 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి',
    'auth.new_farmer': 'కొత్త రైతా? ఇక్కడ నమోదు చేసుకోండి',
  },

  ta: {
    // Tamil
    'platform.title': 'பொது வேளாண் கொள்முதல் தளம்',
    'nav.home': 'முகப்பு',
    'nav.centres': 'கொள்முதல் மையங்கள்',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.contact': 'தொடர்புக்கு',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.login': 'உள்நுழைக',
    'nav.register': 'விவசாயி பதிவு',
    'nav.my_bookings': 'எனது முன்பதிவுகள்',
    'nav.live_queue': 'நேரடி வரிசை',
    'nav.transactions': 'பரிவர்த்தனைகள்',
    'nav.notifications': 'அறிவிப்புகள்',
    'nav.profile': 'விவசாயி சுயவிவரம்',
    'nav.logout': 'வெளியேறு',
    'theme.dark': 'இருண்ட பயன்முறை',
    'theme.light': 'ஒளி பயன்முறை',
    'hero.headline': 'ஸ்மார்ட் கொள்முதல். குறைந்த காத்திருப்பு.',
    'hero.subheadline': 'உங்கள் கொள்முதல் நேரத்தை முன்பதிவு செய்யுங்கள், நேரடி வரிசையை கண்காணிக்கவும், கவுண்டரில் கூட்ட நெரிசலின்றி உங்கள் கட்டணத்தை வங்கியில் நேரடியாகப் பெறவும்.',
    'hero.register': 'விவசாயியாக பதிவு செய்க',
    'hero.find_centres': 'கொள்முதல் மையத்தைக் கண்டறியவும்',
    'dash.welcome_back': 'மீண்டும் வருக,',
    'dash.welcome_default': 'ஃபார்ம்லிங்க் தளத்திற்கு வரவேற்கிறோம்',
    'dash.subtitle': 'இன்றைய உங்கள் பயிர்கள், வரிசை அட்டவணைகள் மற்றும் கொடுப்பனவுகள்.',
    'dash.upcoming_booking': 'வரவிருக்கும் முன்பதிவு',
    'dash.live_queue_pos': 'நேரடி வரிசை நிலை',
    'dash.completed_txns': 'முடிக்கப்பட்ட கொள்முதல்',
    'dash.total_payments': 'நேரடி வங்கி பரிமாற்றம்',
    'dash.quick_actions': 'விரைவு நடவடிக்கைகள்',
    'dash.book_slot': 'புதிய முன்பதிவு செய்க',
    'dash.find_centres': 'மையங்களைத் தேடுக',
    'dash.track_queue': 'நேரடி வரிசை கண்காணிப்பான்',
    'dash.view_txns': 'கொடுப்பனவு ரசீதுகள்',
    'booking.title': 'பயிர் கொள்முதல் நேர முன்பதிவு',
    'booking.subtitle': 'உங்கள் மண்டிக்கான நேரத்தை முன்கூட்டியே ஒதுக்கி நெரிசலைத் தவிர்க்கவும்.',
    'booking.step1': '1. மையத்தைத் தேர்ந்தெடுக்கவும்',
    'booking.step2': '2. தேதி & நேர ஒதுக்கீடு',
    'booking.step3': '3. பயிர் மற்றும் வாகன விவரங்கள்',
    'booking.confirm_btn': 'முன்பதிவை உறுதிசெய்க',
    'booking.success_title': 'முன்பதிவு உறுதி செய்யப்பட்டது!',
    'queue.title': 'நேரடி வரிசை மற்றும் டோக்கன் கண்காணிப்பு',
    'profile.title': 'விவசாயி சுயவிவரம் மற்றும் அடையாளம்',
    'auth.login_title': 'விவசாயி உள்நுழைவு',
    'auth.register_title': 'புதிய விவசாயி பதிவு',
  },

  pa: {
    // Punjabi
    'platform.title': 'ਸਰਕਾਰੀ ਖੇਤੀਬਾੜੀ ਖਰੀਦ ਪੋਰਟਲ',
    'nav.home': 'ਮੁੱਖ ਪੰਨਾ',
    'nav.centres': 'ਖਰੀਦ ਕੇਂਦਰ / ਮੰਡੀਆਂ',
    'nav.about': 'ਸਾਡੇ ਬਾਰੇ',
    'nav.contact': 'ਸੰਪਰਕ',
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.login': 'ਲਾਗਇਨ',
    'nav.register': 'ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    'nav.my_bookings': 'ਮੇਰੀਆਂ ਬੁਕਿੰਗਾਂ',
    'nav.live_queue': 'ਲਾਈਵ ਕਤਾਰ',
    'nav.transactions': 'ਲੈਣ-ਦੇਣ',
    'nav.notifications': 'ਸੂਚਨਾਵਾਂ',
    'nav.profile': 'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ',
    'nav.logout': 'ਲਾਗ ਆਊਟ',
    'hero.headline': 'ਸਮਾਰਟ ਖਰੀਦ। ਘੱਟ ਇੰਤਜ਼ਾਰ।',
    'hero.subheadline': 'ਆਪਣਾ ਖਰੀਦ ਸਲਾਟ ਬੁੱਕ ਕਰੋ, ਲਾਈਵ ਕਤਾਰ ਟਰੈਕ ਕਰੋ ਅਤੇ ਸਿੱਧਾ ਆਪਣੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਐਮਐਸਪੀ ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਕਰੋ।',
    'hero.register': 'ਕਿਸਾਨ ਵਜੋਂ ਰਜਿਸਟਰ ਕਰੋ',
    'hero.find_centres': 'ਨੇੜਲਾ ਖਰੀਦ ਕੇਂਦਰ ਲੱਭੋ',
    'dash.welcome_back': 'ਜੀ ਆਇਆਂ ਨੂੰ,',
    'dash.welcome_default': 'ਫਾਰਮਲਿੰਕ ਕਨੈਕਟ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ',
    'dash.subtitle': 'ਅੱਜ ਤੁਹਾਡੀ ਫਸਲ, ਕਤਾਰ ਦੀ ਸਥਿਤੀ ਅਤੇ ਭੁਗਤਾਨਾਂ ਦਾ ਵੇਰਵਾ।',
    'dash.upcoming_booking': 'ਅਗਲੀ ਬੁਕਿੰਗ',
    'dash.live_queue_pos': 'ਲਾਈਵ ਕਤਾਰ ਨੰਬਰ',
    'dash.completed_txns': 'ਮੁਕੰਮਲ ਖਰੀਦਾਂ',
    'dash.total_payments': 'ਸਿੱਧਾ ਖਾਤੇ ਵਿੱਚ ਭੁਗਤਾਨ',
    'booking.title': 'ਫਸਲ ਖਰੀਦ ਸਲਾਟ ਬੁਕਿੰਗ',
    'booking.subtitle': 'ਆਪਣੀ ਮੰਡੀ ਡਿਲੀਵਰੀ ਦਾ ਸਮਾਂ ਪਹਿਲਾਂ ਤੈਅ ਕਰੋ ਅਤੇ ਗੇਟ ਤੇ ਲਾਈਨਾਂ ਤੋਂ ਬਚੋ।',
    'booking.confirm_btn': 'ਸਲਾਟ ਪੱਕਾ ਕਰੋ',
    'booking.success_title': 'ਬੁਕਿੰਗ ਸਫਲਤਾਪੂਰਵਕ ਹੋ ਗਈ ਹੈ!',
    'queue.title': 'ਲਾਈਵ ਕਤਾਰ ਅਤੇ ਟੋਕਨ ਟਰੈਕਰ',
    'profile.title': 'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਵੇਰਵੇ',
    'auth.login_title': 'ਕਿਸਾਨ ਪੋਰਟਲ ਲਾਗਇਨ',
    'auth.register_title': 'ਨਵੀਂ ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
  },

  mr: {
    // Marathi
    'platform.title': 'सार्वजनिक कृषी खरेदी मंच',
    'nav.home': 'मुख्यपृष्ठ',
    'nav.centres': 'खरेदी केंद्र',
    'nav.about': 'आमच्याबद्दल',
    'nav.contact': 'संपर्क',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.login': 'लॉगिन',
    'nav.register': 'शेतकरी नोंदणी',
    'nav.my_bookings': 'माझी बुकिंग',
    'nav.live_queue': 'थेट रांग (Live Queue)',
    'nav.transactions': 'व्यवहार',
    'nav.notifications': 'सूचना',
    'nav.profile': 'शेतकरी प्रोफाईल',
    'nav.logout': 'बाहेर पडा',
    'hero.headline': 'स्मार्ट खरेदी. कमी प्रतीक्षा.',
    'hero.subheadline': 'तुमचा खरेदी स्लॉट बुक करा, थेट रांग ट्रॅक करा आणि थेट बँक खात्यात हमीभाव मिळवा.',
    'hero.register': 'शेतकरी म्हणून नोंदणी करा',
    'hero.find_centres': 'खरेदी केंद्र शोधा',
    'dash.welcome_back': 'पुन्हा स्वागत आहे,',
    'dash.welcome_default': 'फार्मलिंक कनेक्टमध्ये आपले स्वागत आहे',
    'dash.subtitle': 'तुमच्या पिकांची स्थिती, रांगेचे वेळापत्रक आणि बँक जमा रक्कम.',
    'dash.upcoming_booking': 'आगामी बुकिंग',
    'dash.live_queue_pos': 'रांगेतील क्रमांक',
    'dash.completed_txns': 'पूर्ण झालेले व्यवहार',
    'dash.total_payments': 'थेट बँक जमा रक्कम',
    'booking.title': 'पीक खरेदी स्लॉट बुकिंग',
    'booking.subtitle': 'मार्केट यार्डमधील गर्दी टाळण्यासाठी तुमची वेळ आधीच आरक्षित करा.',
    'booking.confirm_btn': 'स्लॉट निश्चित करा',
    'booking.success_title': 'बुकिंग यशस्वीरित्या झाली आहे!',
    'queue.title': 'थेट रांग आणि टोकन ट्रॅकर',
    'profile.title': 'शेतकरी प्रोफाईल आणि माहिती',
    'auth.login_title': 'शेतकरी पोर्टल लॉगिन',
    'auth.register_title': 'नवीन शेतकरी नोंदणी',
  },

  bn: {
    // Bengali
    'platform.title': 'সরকারি কৃষি সংগ্রহ পোর্টাল',
    'nav.home': 'হোম',
    'nav.centres': 'সংগ্রহ কেন্দ্র',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.contact': 'যোগাযোগ',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.login': 'লগইন',
    'nav.register': 'কৃষক নিবন্ধন',
    'nav.my_bookings': 'আমার বুকিং',
    'nav.live_queue': 'লাইভ সারি',
    'nav.transactions': 'লেনদেন',
    'nav.notifications': 'বিজ্ঞপ্তি',
    'nav.profile': 'কৃষক প্রোফাইল',
    'nav.logout': 'লগ আউট',
    'hero.headline': 'স্মার্ট ক্রয়। কম অপেক্ষা।',
    'hero.subheadline': 'আপনার ফসল বিক্রির স্লট বুক করুন, লাইভ কিউ ট্র্যাক করুন এবং সরাসরি ব্যাঙ্ক অ্যাকাউন্টে এমএসপি অর্থ পান।',
    'hero.register': 'কৃষক হিসেবে নিবন্ধন করুন',
    'hero.find_centres': 'সংগ্রহ কেন্দ্র খুঁজুন',
    'dash.welcome_back': 'স্বাগতম,',
    'dash.welcome_default': 'ফার্মলিঙ্ক কানেক্টে আপনাকে স্বাগতম',
    'booking.title': 'ফসল সংগ্রহ স্লট বুকিং',
    'booking.confirm_btn': 'স্লট নিশ্চিত করুন',
    'booking.success_title': 'বুকিং নিশ্চিত হয়েছে!',
    'queue.title': 'লাইভ সারি এবং টোকেন ট্র্যাকার',
    'profile.title': 'কৃষক প্রোফাইল এবং বিবরণ',
    'auth.login_title': 'কৃষক পোর্টাল লগইন',
    'auth.register_title': 'নতুন কৃষক নিবন্ধন',
  },

  gu: {
    // Gujarati
    'platform.title': 'જાહેર કૃષિ ખરીદ મંચ',
    'nav.home': 'હોમ',
    'nav.centres': 'ખરીદ કેન્દ્રો',
    'nav.about': 'અમારા વિશે',
    'nav.contact': 'સંપર્ક',
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.login': 'લૉગિન',
    'nav.register': 'ખેડૂત નોંધણી',
    'nav.my_bookings': 'મારી બુકિંગ',
    'nav.live_queue': 'લાઇવ લાઇન',
    'nav.transactions': 'વ્યવહારો',
    'nav.notifications': 'સૂચનાઓ',
    'nav.profile': 'ખેડૂત પ્રોફાઇલ',
    'nav.logout': 'લૉગ આઉટ',
    'hero.headline': 'સ્માર્ટ ખરીદી. ઓછી રાહ.',
    'hero.subheadline': 'તમારો પાક વેચવા માટે સ્લોટ બુક કરો, લાઈવ લાઇન ટ્રેક કરો અને સીધા ખાતામાં ટેકાના ભાવ મેળવો.',
    'hero.register': 'ખેડૂત તરીકે નોંધણી કરો',
    'hero.find_centres': 'ખરીદ કેન્દ્ર શોધો',
    'dash.welcome_back': 'સ્વાગત છે,',
    'dash.welcome_default': 'ફાર્મલિંક કનેક્ટમાં આપનું સ્વાગત છે',
    'booking.title': 'પાક ખરીદ સ્લોટ બુકિંગ',
    'booking.confirm_btn': 'સ્લોટ કન્ફર્મ કરો',
    'booking.success_title': 'બુકિંગ સફળતાપૂર્વક થઈ ગયું!',
    'queue.title': 'લાઇવ લાઇન અને ટોકન ટ્રેકર',
    'profile.title': 'ખેડૂત પ્રોફાઇલ અને વિગતો',
    'auth.login_title': 'ખેડૂત પોર્ટલ લૉગિન',
    'auth.register_title': 'નવા ખેડૂતની નોંધણી',
  },

  kn: {
    // Kannada
    'platform.title': 'ಸಾರ್ವಜನಿಕ ಕೃಷಿ ಖರೀದಿ ವೇದಿಕೆ',
    'nav.home': 'ಮುಖಪುಟ',
    'nav.centres': 'ಖರೀದಿ ಕೇಂದ್ರಗಳು',
    'nav.about': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'nav.contact': 'ಸಂಪರ್ಕಿಸಿ',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.login': 'ಲಾಗಿನ್',
    'nav.register': 'ರೈತರ ನೋಂದಣಿ',
    'nav.my_bookings': 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
    'nav.live_queue': 'ಲೈವ್ ಕ್ಯೂ',
    'nav.transactions': 'ವಹಿವಾಟುಗಳು',
    'nav.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'nav.profile': 'ರೈತರ ಪ್ರೊಫೈಲ್',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',
    'hero.headline': 'ಸ್ಮಾರ್ಟ್ ಖರೀದಿ. ಕಡಿಮೆ ಕಾಯುವಿಕೆ.',
    'hero.subheadline': 'ನಿಮ್ಮ ಬೆಳೆ ಮಾರಾಟದ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ, ಲೈವ್ ಕ್ಯೂ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ನೇರವಾಗಿ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಬೆಂಬಲ ಬೆಲೆ ಪಡೆಯಿರಿ.',
    'hero.register': 'ರೈತರಾಗಿ ನೋಂದಾಯಿಸಿ',
    'hero.find_centres': 'ಖರೀದಿ ಕೇಂದ್ರವನ್ನು ಹುಡುಕಿ',
    'dash.welcome_back': 'ಸ್ವಾಗತ,',
    'dash.welcome_default': 'ಫಾರ್ಮ್‌ಲಿಂಕ್ ಕನೆಕ್ಟ್‌ಗೆ ಸುಸ್ವಾಗತ',
    'booking.title': 'ಬೆಳೆ ಖರೀದಿ ಸ್ಲಾಟ್ ಬುಕಿಂಗ್',
    'booking.confirm_btn': 'ಸ್ಲಾಟ್ ದೃಢೀಕರಿಸಿ',
    'booking.success_title': 'ಬುಕಿಂಗ್ ಯಶಸ್ವಿಯಾಗಿದೆ!',
    'queue.title': 'ಲೈವ್ ಕ್ಯೂ ಮತ್ತು ಟೋಕನ್ ಟ್ರ್ಯಾಕರ್',
    'profile.title': 'ರೈತರ ಪ್ರೊಫೈಲ್ ಮತ್ತು ವಿವರಗಳು',
    'auth.login_title': 'ರೈತ ಪೋರ್ಟಲ್ ಲಾಗಿನ್',
    'auth.register_title': 'ಹೊಸ ರೈತರ ನೋಂದಣಿ',
  },

  ml: {
    // Malayalam
    'platform.title': 'പബ്ലിക് അഗ്രികൾച്ചറൽ പ്രൊക്യൂർമെന്റ് പ്ലാറ്റ്‌ഫോം',
    'nav.home': 'ഹോം',
    'nav.centres': 'സംഭരണ കേന്ദ്രങ്ങൾ',
    'nav.about': 'ഞങ്ങളെക്കുറിച്ച്',
    'nav.contact': 'ബന്ധപ്പെടുക',
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.login': 'ലോഗിൻ',
    'nav.register': 'കർഷക രജിസ്ട്രേഷൻ',
    'nav.my_bookings': 'എന്റെ ബുക്കിംഗുകൾ',
    'nav.live_queue': 'തത്സമയ ക്യൂ',
    'nav.transactions': 'ഇടപാടുകൾ',
    'nav.notifications': 'അറിയിപ്പുകൾ',
    'nav.profile': 'കർഷക പ്രൊഫൈൽ',
    'nav.logout': 'ലോഗ് ഔട്ട്',
    'hero.headline': 'സ്മാർട്ട് സംഭരണം. കുറഞ്ഞ കാത്തിരിപ്പ്.',
    'hero.subheadline': 'നിങ്ങളുടെ സംഭരണ സ്ലോട്ട് ബുക്ക് ചെയ്യുക, തത്സമയ ക്യൂ ട്രാക്ക് ചെയ്യുക, നേരിട്ട് ബാങ്ക് അക്കൗണ്ടിലേക്ക് പണം സ്വീകരിക്കുക.',
    'hero.register': 'കർഷകനായി രജിസ്റ്റർ ചെയ്യുക',
    'hero.find_centres': 'സംഭരണ കേന്ദ്രം കണ്ടെത്തുക',
    'dash.welcome_back': 'സ്വാഗതം,',
    'dash.welcome_default': 'ഫാംലിങ്ക് കണക്റ്റിലേക്ക് സ്വാഗതം',
    'booking.title': 'വിള സംഭരണ സ്ലോട്ട് ബുക്കിംഗ്',
    'booking.confirm_btn': 'സ്ലോട്ട് സ്ഥിരീകരിക്കുക',
    'booking.success_title': 'ബുക്കിംഗ് വിജയകരമായി പൂർത്തിയായി!',
    'queue.title': 'തത്സമയ ക്യൂ & ടോക്കൺ ട്രാക്കർ',
    'profile.title': 'കർഷക പ്രൊഫൈലും വിശദാംശങ്ങളും',
    'auth.login_title': 'കർഷക പോർട്ടൽ ലോഗിൻ',
    'auth.register_title': 'പുതിയ കർഷക രജിസ്ട്രേഷൻ',
  },

  or: {
    // Odia
    'platform.title': 'ସରକାରୀ କୃଷି ସଂଗ୍ରହ ପୋର୍ଟାଲ',
    'nav.home': 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
    'nav.centres': 'କ୍ରୟ କେନ୍ଦ୍ର (ମଣ୍ଡି)',
    'nav.about': 'ଆମ ବିଷୟରେ',
    'nav.contact': 'ଯୋଗାଯୋଗ',
    'nav.dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'nav.login': 'ଲଗଇନ୍',
    'nav.register': 'କୃଷକ ପଞ୍ଜୀକରଣ',
    'nav.my_bookings': 'ମୋର ବୁକିଂ',
    'nav.live_queue': 'ଲାଇଭ୍ ଧାଡି',
    'nav.transactions': 'କାରବାର',
    'nav.notifications': 'ସୂଚନା',
    'nav.profile': 'କୃଷକ ପ୍ରୋଫାଇଲ୍',
    'nav.logout': 'ଲଗ୍ ଆଉଟ୍',
    'hero.headline': 'ସ୍ମାର୍ଟ କ୍ରୟ। କମ୍ ଅପେକ୍ଷା।',
    'hero.subheadline': 'ଆପଣଙ୍କର ଫସଲ ବିକ୍ରୟ ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ ଏବଂ ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଖାତାରେ ସରକାରୀ ମୂଲ୍ୟ ପାଆନ୍ତୁ।',
    'hero.register': 'କୃଷକ ଭାବରେ ପଞ୍ଜୀକରଣ କରନ୍ତୁ',
    'hero.find_centres': 'କ୍ରୟ କେନ୍ଦ୍ର ଖୋଜନ୍ତୁ',
    'dash.welcome_back': 'ସ୍ୱାଗତ,',
    'dash.welcome_default': 'ଫାର୍ମଲିଙ୍କ୍ କନେକ୍ଟକୁ ସ୍ୱାଗତ',
    'booking.title': 'ଫସଲ ବିକ୍ରୟ ସ୍ଲଟ୍ ବୁକିଂ',
    'booking.confirm_btn': 'ସ୍ଲଟ୍ ନିଶ୍ଚିତ କରନ୍ତୁ',
    'booking.success_title': 'ବୁକିଂ ସଫଳ ହେଲା!',
    'queue.title': 'ଲାଇଭ୍ ଧାଡି ଏବଂ ଟୋକନ୍ ଟ୍ରାକର୍',
    'profile.title': 'କୃଷକ ପ୍ରୋଫାଇଲ୍ ଏବଂ ବିବରଣୀ',
    'auth.login_title': 'କୃଷକ ପୋର୍ଟାଲ୍ ଲଗଇନ୍',
    'auth.register_title': 'ନୂତନ କୃଷକ ପଞ୍ଜୀକରଣ',
  },

  as: {
    // Assamese
    'platform.title': 'ৰাজহুৱা কৃষি ক্ৰয় পৰ্টেল',
    'nav.home': 'মূল পৃষ্ঠা',
    'nav.centres': 'ক্ৰয় কেন্দ্ৰ / মণ্ডী',
    'nav.about': 'আমাৰ বিষয়ে',
    'nav.contact': 'যোগাযোগ',
    'nav.dashboard': 'ডেশ্ববৰ্ড',
    'nav.login': 'লগইন',
    'nav.register': 'কৃষক পঞ্জীয়ন',
    'nav.my_bookings': 'মোৰ বুকিং',
    'nav.live_queue': 'লাইভ শাৰী',
    'nav.transactions': 'লেনদেন আৰু পৰিশোধ',
    'nav.notifications': 'জাননীসমূহ',
    'nav.profile': 'কৃষক প্ৰফাইল',
    'nav.logout': 'লগ আউট',
    'hero.headline': 'স্মাৰ্ট ক্ৰয়। কম অপেক্ষা।',
    'hero.subheadline': 'আপোনাৰ ফচল বিক্ৰীৰ স্লট বুক কৰক, লাইভ শাৰী ট্ৰেক কৰক আৰু পোনপটীয়াকৈ বেংক একাউণ্টত এম এছ পি লাভ কৰক।',
    'hero.register': 'কৃষক হিচাপে পঞ্জীয়ন কৰক',
    'hero.find_centres': 'ক্ৰয় কেন্দ্ৰ সন্ধান কৰক',
    'dash.welcome_back': 'পুনৰ স্বাগতম,',
    'dash.welcome_default': 'AgriSetu লৈ স্বাগতম',
    'dash.subtitle': 'আজি আপোনাৰ শস্য, শাৰীৰ সময়সূচী আৰু বেংক পৰিশোধৰ তথ্য।',
    'booking.title': 'শস্য ক্ৰয়ৰ স্লট বুকিং',
    'booking.confirm_btn': 'স্লট নিশ্চিত কৰক',
    'booking.success_title': 'বুকিং নিশ্চিত হৈছে!',
    'queue.title': 'লাইভ শাৰী আৰু টোকেন ট্ৰেকাৰ',
    'profile.title': 'কৃষক প্ৰফাইল আৰু পৰিচয়',
    'auth.login_title': 'কৃষক পৰ্টেলত প্ৰৱেশ',
    'auth.register_title': 'নতুন কৃষক পঞ্জীয়ন',
  },

  ur: {
    // Urdu
    'platform.title': 'عوامی زرعی خریداری پورٹل',
    'nav.home': 'ہوم',
    'nav.centres': 'خریداری مراکز',
    'nav.about': 'ہمارے بارے میں',
    'nav.contact': 'رابطہ کریں',
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.login': 'لاگ ان',
    'nav.register': 'کسان رجسٹریشن',
    'nav.my_bookings': 'میری بکنگز',
    'nav.live_queue': 'لائیو قطار',
    'nav.transactions': 'لین دین اور ادائیگی',
    'nav.notifications': 'اطلاعات',
    'nav.profile': 'کسان پروفائل',
    'nav.logout': 'لاگ آؤٹ',
    'hero.headline': 'سمارٹ خریداری۔ کم انتظار۔',
    'hero.subheadline': 'اپنی فصل کی فراہمی کا سلاٹ بک کریں، لائیو قطار ٹریک کریں، اور براہ راست بینک میں ایم ایس پی حاصل کریں۔',
    'hero.register': 'بطور کسان رجسٹر کریں',
    'hero.find_centres': 'قریبی خریداری مرکز تلاش کریں',
    'dash.welcome_back': 'خوش آمدید،',
    'dash.welcome_default': 'ایگری سیتو میں خوش آمدید',
    'booking.title': 'فصل خریداری کا وقت بک کریں',
    'booking.confirm_btn': 'سلاٹ کنفرم کریں',
    'booking.success_title': 'بکنگ کامیاب ہو گئی!',
    'queue.title': 'لائیو قطار اور ٹوکن ٹریکر',
    'profile.title': 'کسان پروفائل اور شناخت',
    'auth.login_title': 'کسان پورٹل لاگ ان',
    'auth.register_title': 'نیا کسان رجسٹریشن',
  },

  bho: {
    // Bhojpuri
    'platform.title': 'सार्वजनिक कृषि खरीद मंच',
    'nav.home': 'मुख्य पृष्ठ',
    'nav.centres': 'खरीद केंद्र',
    'nav.about': 'हमार बारे में',
    'nav.contact': 'संपर्क करीं',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.login': 'लॉगिन करीं',
    'nav.register': 'किसान पंजीकरण',
    'nav.my_bookings': 'हमार बुकिंग',
    'nav.live_queue': 'लाइव लाइन (कतार)',
    'nav.transactions': 'खाता में भुगतानी',
    'nav.notifications': 'सूचना',
    'nav.profile': 'किसान प्रोफाइल',
    'nav.logout': 'लॉग आउट',
    'hero.headline': 'स्मार्ट खरीद। कम इंतजार।',
    'hero.subheadline': 'फसल बेचे के स्लॉट बुक करीं, लाइव लाइन देखीं आ सोझै बैंक खाता में एमएसपी के पईसा पाईं।',
    'hero.register': 'किसान के रूप में रजिस्टर करीं',
    'hero.find_centres': 'खरीद केंद्र खोजीं',
    'dash.welcome_back': 'फेरु से स्वागत बा,',
    'dash.welcome_default': 'AgriSetu में राउर स्वागत बा',
    'booking.title': 'फसल खरीद स्लॉट बुकिंग',
    'booking.confirm_btn': 'स्लॉट पक्का करीं',
    'booking.success_title': 'बुकिंग पक्की हो गईल!',
    'queue.title': 'लाइव लाइन आ टोकन ट्रैकर',
    'profile.title': 'किसान प्रोफाइल आ जानकारी',
    'auth.login_title': 'किसान पोर्टल लॉगिन',
    'auth.register_title': 'नया किसान पंजीकरण',
  },

  ma: {
    // Maithili
    'platform.title': 'सार्वजनिक कृषि खरीद पोर्टल',
    'nav.home': 'गृह पृष्ठ',
    'nav.centres': 'खरीद केन्द्र',
    'nav.about': 'हमरा सभक विषय में',
    'nav.contact': 'सम्पर्क करू',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.login': 'लॉगिन करू',
    'nav.register': 'किसान पंजीकरण',
    'nav.my_bookings': 'हमर बुकिंग',
    'nav.live_queue': 'लाइव पाँती (कतार)',
    'nav.transactions': 'लेनदेन आ भुगतान',
    'nav.notifications': 'सूचना',
    'nav.profile': 'किसान प्रोफाइल',
    'nav.logout': 'लॉग आउट',
    'hero.headline': 'स्मार्ट खरीद। कम प्रतीक्षा।',
    'hero.subheadline': 'अपन फसल बेचबाक स्लॉट बुक करू, लाइव कतार देखू आ सीधे बैंक खाता में एमएसपी प्राप्त करू।',
    'hero.register': 'किसानक रूप में पंजीकृत करू',
    'hero.find_centres': 'खरीद केंद्र खोजू',
    'dash.welcome_back': 'पुनः स्वागत अछि,',
    'dash.welcome_default': 'AgriSetu में अहाँक स्वागत अछि',
    'booking.title': 'फसल खरीद स्लॉट बुकिंग',
    'booking.confirm_btn': 'स्लॉट निश्चित करू',
    'booking.success_title': 'बुकिंग निश्चित भ गेल!',
    'queue.title': 'लाइव पाँती आ टोकन ट्रैकर',
    'profile.title': 'किसान प्रोफाइल आ परिचय',
    'auth.login_title': 'किसान पोर्टल लॉगिन',
    'auth.register_title': 'नवीन किसान पंजीकरण',
  },

  sa: {
    // Sanskrit
    'platform.title': 'सार्वजनिक-कृषि-क्रयण-मञ्चम्',
    'nav.home': 'मुख्यपृष्ठम्',
    'nav.centres': 'क्रयणकेन्द्राणि',
    'nav.about': 'अस्माकं विषये',
    'nav.contact': 'सम्पर्कः',
    'nav.dashboard': 'फलकम्',
    'nav.login': 'प्रवेशः',
    'nav.register': 'कृषकपञ्जीकरणम्',
    'nav.my_bookings': 'मम आरक्षणाणि',
    'nav.live_queue': 'प्रत्यक्षपङ्क्तिः',
    'nav.transactions': 'धनव्यवहाराः',
    'nav.notifications': 'सूचनाः',
    'nav.profile': 'कृषकविवरणम्',
    'nav.logout': 'निर्गमः',
    'hero.headline': 'सुलभं क्रयणम्। न्यूनप्रतीक्षा।',
    'hero.subheadline': 'स्वशस्यविक्रयणाय समयम् आरक्षयन्तु, प्रत्यक्षपङ्क्तिं पश्यन्तु, साक्षात् कोशे न्यूनतमसमर्थनमूल्यं प्राप्नुवन्तु च।',
    'hero.register': 'कृषकरूपेण पञ्जीकरणं कुर्वन्तु',
    'hero.find_centres': 'क्रयणकेन्द्रं अन्विष्यन्तु',
    'dash.welcome_back': 'पुनः स्वागतम्,',
    'dash.welcome_default': 'AgriSetu मध्ये भवतां स्वागतम्',
    'booking.title': 'शस्यक्रयणसमयस्य आरक्षणम्',
    'booking.confirm_btn': 'आरक्षणं दृढीकुर्वन्तु',
    'booking.success_title': 'आरक्षणं सफलम् अभवत्!',
    'queue.title': 'प्रत्यक्षपङ्क्तिः टोकन-अनुधावकः च',
    'profile.title': 'कृषकपरिचयपत्रं विवरणं च',
    'auth.login_title': 'कृषकप्रवेशद्वारम्',
    'auth.register_title': 'नूतनकृषकपञ्जीकरणम्',
  },
};

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string, fallback?: string, vars?: Record<string, string | number>) => string;
  activeLanguageInfo: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('farmlink_language');
    if (saved && SUPPORTED_LANGUAGES.some((l) => l.code === saved)) {
      return saved as LanguageCode;
    }
    return 'en';
  });

  const setLanguage = (code: LanguageCode) => {
    setCurrentLanguageState(code);
    localStorage.setItem('farmlink_language', code);
    const langInfo = SUPPORTED_LANGUAGES.find((l) => l.code === code);
    if (langInfo?.direction === 'rtl') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
    document.documentElement.lang = code;
  };

  useEffect(() => {
    const langInfo = SUPPORTED_LANGUAGES.find((l) => l.code === currentLanguage);
    if (langInfo?.direction === 'rtl') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  const t = (key: string, fallback?: string, vars?: Record<string, string | number>): string => {
    let result =
      LOCALES[currentLanguage]?.[key] ||
      TRANSLATIONS[currentLanguage]?.[key] ||
      LOCALES.en?.[key] ||
      TRANSLATIONS.en?.[key] ||
      fallback ||
      key;

    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        result = result.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
      });
    }

    return result;
  };

  const activeLanguageInfo =
    SUPPORTED_LANGUAGES.find((l) => l.code === currentLanguage) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        t,
        activeLanguageInfo,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Aliases for compatibility
export const useLanguageVoice = useLanguage;
export const LanguageVoiceProvider = LanguageProvider;
